# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: knn-vm-lab7
  namespace: threekov-lab7
spec:
  type: ClusterIP 
  selector:
    app: knn-vm-lab7
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
