# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: knn-vm-lab7
  namespace: threekov-lab7
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30082
  selector:
    app: knn-vm-lab7
